# Generated by Django 4.0 on 2021-12-13 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountValue', models.IntegerField()),
                ('accountType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('perOrderFees', models.IntegerField()),
                ('currencyConversionRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('isSuperUser', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TotalStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueTickers', models.BigIntegerField()),
                ('totalInvested', models.BigIntegerField()),
                ('quantityOfTrades', models.BigIntegerField()),
                ('netProfit', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Specific_Stock_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('netProfit', models.IntegerField()),
                ('exchange', models.CharField(max_length=100)),
                ('amountShares', models.IntegerField()),
                ('currentValue', models.IntegerField()),
                ('stockHistoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.totalstockhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation', models.BigIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofFile', models.CharField(max_length=100)),
                ('numOfOrders', models.IntegerField()),
                ('dateRequested', models.DateField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.account')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('purchasePrice', models.IntegerField()),
                ('purchaseTime', models.DateTimeField(max_length=100)),
                ('orderReqID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.orderform')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation', models.BigIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('purchasePrice', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation', models.BigIntegerField()),
                ('bank', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation', models.BigIntegerField()),
                ('interest', models.CharField(max_length=100)),
                ('principal', models.CharField(max_length=100)),
                ('maturityDate', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.user')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.user'),
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('Yield', models.IntegerField()),
                ('TaxRate', models.IntegerField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.specific_stock_history')),
            ],
            options={
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
