# Generated by Django 4.0 on 2021-12-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onestock_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonds',
            name='maturityDate',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bonds',
            name='valuation',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cash',
            name='valuation',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='valuation',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='purchasePrice',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='quantity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='valuation',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='valuation',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='specific_stock_history',
            name='stockHistoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.totalstockhistory'),
        ),
        migrations.AlterField(
            model_name='totalstockhistory',
            name='netProfit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='totalstockhistory',
            name='quantityOfTrades',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='totalstockhistory',
            name='totalInvested',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='totalstockhistory',
            name='uniqueTickers',
            field=models.BigIntegerField(),
        ),
    ]
