# Generated by Django 4.0 on 2021-12-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onestock_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specific_Stock_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('netProfit', models.IntegerField()),
                ('exchange', models.CharField(max_length=100)),
                ('amountShares', models.IntegerField()),
                ('currentValue', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onestock_backend.user')),
            ],
        ),
    ]
