# Generated by Django 4.0 on 2021-12-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestock_backend', '0002_alter_bonds_maturitydate_alter_bonds_valuation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountValue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='currencyConversionRate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='perOrderFees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='TaxRate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='Yield',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchasePrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='numOfOrders',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specific_stock_history',
            name='amountShares',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specific_stock_history',
            name='currentValue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specific_stock_history',
            name='netProfit',
            field=models.IntegerField(),
        ),
    ]
